### ISSUE TITLE
Can't install (spree 0.30.0, Rails 3)

### ISSUE THREAD

**Issue by evansj** [jaymendoza/spree-blogging-spree#11]
<pre>

$ bundle install
Fetching http://github.com/divineforest/spree-blogging-spree.git
remote: Counting objects: 693, done.
remote: Compressing objects: 100% (353/353), done.
remote: Total 693 (delta 291), reused 646 (delta 281)
Receiving objects: 100% (693/693), 98.48 KiB, done.
Resolving deltas: 100% (291/291), done.
Fetching source index for http://rubygems.org/
Could not find gem 'spree-blogging-spree (>= 0, runtime)' in http://github.com/divineforest/spree-blogging-spree.git (at master).
Source does not contain any versions of 'spree-blogging-spree (>= 0, runtime)'

$ grep -v ^# Gemfile
source 'http://rubygems.org'
gem 'rails', '>=3.0.1'
gem 'mysql2'
gem 'spree', '>=0.30.0'
gem 'spree_static_content', :git => 'https://github.com/spree/spree-static-content.git'
gem 'formtastic', :git => 'git://github.com/justinfrench/formtastic.git'
gem 'dynamic_form', :git => 'git://github.com/rails/dynamic_form.git'
gem 'contact_us', :require => 'contact_us', :git => 'git://github.com/greendog/spree_contact_us.git'
gem 'spree_i18n', :git => 'git://github.com/spree/spree_i18n.git' 
gem 'spree-blogging-spree', :git => 'http://github.com/divineforest/spree-blogging-spree.git'

</pre>

Thanks :)

**Comment by erikkallen** [comment]
Had the same issue you need to change gem 'spree-blogging-spree', :git => 'http://github.com/divineforest/spree-blogging-spree.git'

into:

gem 'spree_blogging_spree', :git => 'http://github.com/divineforest/spree-blogging-spree.git'

then it works

**Comment by IsraelBuitronD** [comment]
I tried to install:

```
$ rails plugin install git://github.com/jaymendoza/spree-blogging-spree.git
Initialized empty Git repository in /home/neoriddle/my_app/vendor/plugins/spree-blogging-spree/.git/
remote: Counting objects: 71, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 71 (delta 7), reused 49 (delta 5)
Unpacking objects: 100% (71/71), done.
From git://github.com/jaymendoza/spree-blogging-spree
 * branch            HEAD       -> FETCH_HEAD
$ rake db:migrate -v
rake aborted!
undefined local variable or method `map' for main:Object

Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

A complete trace using `--trace` is here:

```
$ rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
undefined local variable or method `map' for main:Object
/home/neoriddle/my_app/vendor/plugins/spree-blogging-spree/config/routes.rb:1
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `load'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `load'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596:in `new_constants_in'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:235:in `load'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application.rb:127:in `reload_routes!'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application.rb:127:in `each'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application.rb:127:in `reload_routes!'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application.rb:120:in `routes_reloader'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/file_update_checker.rb:32:in `call'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/file_update_checker.rb:32:in `execute_if_updated'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application/finisher.rb:51
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application/finisher.rb:52:in `call'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application/finisher.rb:52
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/initializable.rb:25:in `instance_exec'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/initializable.rb:25:in `run'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/initializable.rb:50:in `run_initializers'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/initializable.rb:49:in `each'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/initializable.rb:49:in `run_initializers'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application.rb:134:in `initialize!'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application.rb:77:in `send'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application.rb:77:in `method_missing'
/home/neoriddle/my_app/config/environment.rb:5
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596:in `new_constants_in'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application.rb:103:in `require_environment!'
/usr/lib/ruby/gems/1.8/gems/railties-3.0.9/lib/rails/application.rb:218:in `initialize_tasks'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:205:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:158:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:176:in `invoke_prerequisites'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:157:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:62:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2/bin/rake:32
/usr/bin/rake:19:in `load'
/usr/bin/rake:19
Tasks: TOP => db:migrate => environment
```

And finally line 1 in `vendor/plugins/spree-blogging-spree/config/routes.rb` file is:

```
map.entry_permalink 'blog/:year/:month/:day/:slug', :controller => 'blog_entries', :action => 'show'
```

**Comment by erikkallen** [comment]
try this:

remove the one entry from your routes file then migrate then add the entry again, probably it tries to load a blog model before it exists
